name = "fscan"
pname = "fscan.exe "
ppname = "None"

[[nomust_noinput_args]]
arg_name = "-np "
arg_more = "跳过存货检测"
arg_enable = false

[[nomust_noinput_args]]
arg_name = "-nopoc "
arg_more = "跳过Web Poc扫描"
arg_enable = false

[[nomust_noinput_args]]
arg_name = "-nobr "
arg_more = "跳过爆破"
arg_enable = false

[[nomust_noinput_args]]
arg_name = "-no "
arg_more = "不保存输出"
arg_enable = false

[[nomust_input_args]]
arg_name = "-h "
arg_more = "扫描IP或IP段"
arg_text = "192.168.1.1/24"
arg_enable = true

[[nomust_input_args]]
arg_name = "-u "
arg_more = "扫描单个url"
arg_text = "http://127.0.0.1"
arg_enable = false

[[nomust_input_args]]
arg_name = "-hf "
arg_more = "扫描文件内的ip"
arg_text = "ip.txt"
arg_enable = false

[[nomust_input_args]]
arg_name = "-rf "
arg_more = "Redis写公钥"
arg_text = "~/.ssh/id_rsa.pub"
arg_enable = false

[[nomust_input_args]]
arg_name = "-rs "
arg_more = "redis计划任务反弹shell"
arg_text = "127.0.0.1:2333"
arg_enable = false

[[nomust_input_args]]
arg_name = "-c "
arg_more = "ssh爆破成功后执行命令"
arg_text = "uname -a"
arg_enable = false

[[nomust_input_args]]
arg_name = "-m "
arg_more = "指定模块[ssh,sql,ms17010]"
arg_text = "all"
arg_enable = false

[[nomust_input_args]]
arg_name = "-p "
arg_more = "指定端口"
arg_text = "8022"
arg_enable = false

[[nomust_input_args]]
arg_name = "-userf "
arg_more = "加载用户名字典爆破"
arg_text = "res/SecLists/Usernames/top-usernames-shortlist.txt"
arg_enable = false

[[nomust_input_args]]
arg_name = "-pwdf "
arg_more = "加载密码字典爆破"
arg_text = "res/SecLists/Passwords/cirt-default-passwords.txt"
arg_enable = false

[[nomust_input_args]]
arg_name = "-o "
arg_more = "保存结果"
arg_text = "nul"
arg_enable = false

[[nomust_input_args]]
arg_name = "-t "
arg_more = "线程数量"
arg_text = "600"
arg_enable = false

[[nomust_input_args]]
arg_name = "-proxy "
arg_more = "设置http代理"
arg_text = "8080"
arg_enable = false

[[nomust_input_args]]
arg_name = "-socks5 "
arg_more = "设置socks5代理"
arg_text = "127.0.0.1:1080"
arg_enable = false



